import 'package:flutter/material.dart';

class CountryCode {
  final String name;
  final String dialCode;
  final String code;
  final String flag;

  CountryCode({
    required this.name,
    required this.dialCode,
    required this.code,
    required this.flag,
  });

  @override
  String toString() => "$dialCode";

  static List<CountryCode> getCommonCountries() {
    return [
      CountryCode(
        name: "United States",
        dialCode: "+1",
        code: "US",
        flag: "🇺🇸",
      ),
      CountryCode(name: "India", dialCode: "+91", code: "IN", flag: "🇮🇳"),
      CountryCode(
        name: "United Kingdom",
        dialCode: "+44",
        code: "GB",
        flag: "🇬🇧",
      ),
      CountryCode(name: "Canada", dialCode: "+1", code: "CA", flag: "🇨🇦"),
      CountryCode(name: "Australia", dialCode: "+61", code: "AU", flag: "🇦🇺"),
      CountryCode(name: "Germany", dialCode: "+49", code: "DE", flag: "🇩🇪"),
      CountryCode(name: "France", dialCode: "+33", code: "FR", flag: "🇫🇷"),
      CountryCode(name: "China", dialCode: "+86", code: "CN", flag: "🇨🇳"),
      CountryCode(name: "Japan", dialCode: "+81", code: "JP", flag: "🇯🇵"),
      CountryCode(name: "Brazil", dialCode: "+55", code: "BR", flag: "🇧🇷"),
    ];
  }

  static List<CountryCode> getAllCountries() {
    return [
      CountryCode(
        name: "Afghanistan",
        dialCode: "+93",
        code: "AF",
        flag: "🇦🇫",
      ),
      CountryCode(name: "Albania", dialCode: "+355", code: "AL", flag: "🇦🇱"),
      CountryCode(name: "Algeria", dialCode: "+213", code: "DZ", flag: "🇩🇿"),
      CountryCode(name: "Andorra", dialCode: "+376", code: "AD", flag: "🇦🇩"),
      CountryCode(name: "Angola", dialCode: "+244", code: "AO", flag: "🇦🇴"),
      CountryCode(
        name: "Antigua and Barbuda",
        dialCode: "+1",
        code: "AG",
        flag: "🇦🇬",
      ),
      CountryCode(name: "Argentina", dialCode: "+54", code: "AR", flag: "🇦🇷"),
      CountryCode(name: "Armenia", dialCode: "+374", code: "AM", flag: "🇦🇲"),
      CountryCode(name: "Australia", dialCode: "+61", code: "AU", flag: "🇦🇺"),
      CountryCode(name: "Austria", dialCode: "+43", code: "AT", flag: "🇦🇹"),
      CountryCode(
        name: "Azerbaijan",
        dialCode: "+994",
        code: "AZ",
        flag: "🇦🇿",
      ),
      CountryCode(name: "Bahamas", dialCode: "+1", code: "BS", flag: "🇧🇸"),
      CountryCode(name: "Bahrain", dialCode: "+973", code: "BH", flag: "🇧🇭"),
      CountryCode(
        name: "Bangladesh",
        dialCode: "+880",
        code: "BD",
        flag: "🇧🇩",
      ),
      CountryCode(name: "Barbados", dialCode: "+1", code: "BB", flag: "🇧🇧"),
      CountryCode(name: "Belarus", dialCode: "+375", code: "BY", flag: "🇧🇾"),
      CountryCode(name: "Belgium", dialCode: "+32", code: "BE", flag: "🇧🇪"),
      CountryCode(name: "Belize", dialCode: "+501", code: "BZ", flag: "🇧🇿"),
      CountryCode(name: "Benin", dialCode: "+229", code: "BJ", flag: "🇧🇯"),
      CountryCode(name: "Bhutan", dialCode: "+975", code: "BT", flag: "🇧🇹"),
      CountryCode(name: "Bolivia", dialCode: "+591", code: "BO", flag: "🇧🇴"),
      CountryCode(
        name: "Bosnia and Herzegovina",
        dialCode: "+387",
        code: "BA",
        flag: "🇧🇦",
      ),
      CountryCode(name: "Botswana", dialCode: "+267", code: "BW", flag: "🇧🇼"),
      CountryCode(name: "Brazil", dialCode: "+55", code: "BR", flag: "🇧🇷"),
      CountryCode(name: "Brunei", dialCode: "+673", code: "BN", flag: "🇧🇳"),
      CountryCode(name: "Bulgaria", dialCode: "+359", code: "BG", flag: "🇧🇬"),
      CountryCode(
        name: "Burkina Faso",
        dialCode: "+226",
        code: "BF",
        flag: "🇧🇫",
      ),
      CountryCode(name: "Burundi", dialCode: "+257", code: "BI", flag: "🇧🇮"),
      CountryCode(name: "Cambodia", dialCode: "+855", code: "KH", flag: "🇰🇭"),
      CountryCode(name: "Cameroon", dialCode: "+237", code: "CM", flag: "🇨🇲"),
      CountryCode(name: "Canada", dialCode: "+1", code: "CA", flag: "🇨🇦"),
      CountryCode(
        name: "Cape Verde",
        dialCode: "+238",
        code: "CV",
        flag: "🇨🇻",
      ),
      CountryCode(
        name: "Central African Republic",
        dialCode: "+236",
        code: "CF",
        flag: "🇨🇫",
      ),
      CountryCode(name: "Chad", dialCode: "+235", code: "TD", flag: "🇹🇩"),
      CountryCode(name: "Chile", dialCode: "+56", code: "CL", flag: "🇨🇱"),
      CountryCode(name: "China", dialCode: "+86", code: "CN", flag: "🇨🇳"),
      CountryCode(name: "Colombia", dialCode: "+57", code: "CO", flag: "🇨🇴"),
      CountryCode(name: "Comoros", dialCode: "+269", code: "KM", flag: "🇰🇲"),
      CountryCode(name: "Congo", dialCode: "+242", code: "CG", flag: "🇨🇬"),
      CountryCode(
        name: "Democratic Republic of the Congo",
        dialCode: "+243",
        code: "CD",
        flag: "🇨🇩",
      ),
      CountryCode(
        name: "Costa Rica",
        dialCode: "+506",
        code: "CR",
        flag: "🇨🇷",
      ),
      CountryCode(name: "Croatia", dialCode: "+385", code: "HR", flag: "🇭🇷"),
      CountryCode(name: "Cuba", dialCode: "+53", code: "CU", flag: "🇨🇺"),
      CountryCode(name: "Cyprus", dialCode: "+357", code: "CY", flag: "🇨🇾"),
      CountryCode(
        name: "Czech Republic",
        dialCode: "+420",
        code: "CZ",
        flag: "🇨🇿",
      ),
      CountryCode(name: "Denmark", dialCode: "+45", code: "DK", flag: "🇩🇰"),
      CountryCode(name: "Djibouti", dialCode: "+253", code: "DJ", flag: "🇩🇯"),
      CountryCode(name: "Dominica", dialCode: "+1", code: "DM", flag: "🇩🇲"),
      CountryCode(
        name: "Dominican Republic",
        dialCode: "+1",
        code: "DO",
        flag: "🇩🇴",
      ),
      CountryCode(
        name: "East Timor",
        dialCode: "+670",
        code: "TL",
        flag: "🇹🇱",
      ),
      CountryCode(name: "Ecuador", dialCode: "+593", code: "EC", flag: "🇪🇨"),
      CountryCode(name: "Egypt", dialCode: "+20", code: "EG", flag: "🇪🇬"),
      CountryCode(
        name: "El Salvador",
        dialCode: "+503",
        code: "SV",
        flag: "🇸🇻",
      ),
      CountryCode(
        name: "Equatorial Guinea",
        dialCode: "+240",
        code: "GQ",
        flag: "🇬🇶",
      ),
      CountryCode(name: "Eritrea", dialCode: "+291", code: "ER", flag: "🇪🇷"),
      CountryCode(name: "Estonia", dialCode: "+372", code: "EE", flag: "🇪🇪"),
      CountryCode(name: "Ethiopia", dialCode: "+251", code: "ET", flag: "🇪🇹"),
      CountryCode(name: "Fiji", dialCode: "+679", code: "FJ", flag: "🇫🇯"),
      CountryCode(name: "Finland", dialCode: "+358", code: "FI", flag: "🇫🇮"),
      CountryCode(name: "France", dialCode: "+33", code: "FR", flag: "🇫🇷"),
      CountryCode(name: "Gabon", dialCode: "+241", code: "GA", flag: "🇬🇦"),
      CountryCode(name: "Gambia", dialCode: "+220", code: "GM", flag: "🇬🇲"),
      CountryCode(name: "Georgia", dialCode: "+995", code: "GE", flag: "🇬🇪"),
      CountryCode(name: "Germany", dialCode: "+49", code: "DE", flag: "🇩🇪"),
      CountryCode(name: "Ghana", dialCode: "+233", code: "GH", flag: "🇬🇭"),
      CountryCode(name: "Greece", dialCode: "+30", code: "GR", flag: "🇬🇷"),
      CountryCode(name: "Grenada", dialCode: "+1", code: "GD", flag: "🇬🇩"),
      CountryCode(
        name: "Guatemala",
        dialCode: "+502",
        code: "GT",
        flag: "🇬🇹",
      ),
      CountryCode(name: "Guinea", dialCode: "+224", code: "GN", flag: "🇬🇳"),
      CountryCode(
        name: "Guinea-Bissau",
        dialCode: "+245",
        code: "GW",
        flag: "🇬🇼",
      ),
      CountryCode(name: "Guyana", dialCode: "+592", code: "GY", flag: "🇬🇾"),
      CountryCode(name: "Haiti", dialCode: "+509", code: "HT", flag: "🇭🇹"),
      CountryCode(name: "Honduras", dialCode: "+504", code: "HN", flag: "🇭🇳"),
      CountryCode(name: "Hungary", dialCode: "+36", code: "HU", flag: "🇭🇺"),
      CountryCode(name: "Iceland", dialCode: "+354", code: "IS", flag: "🇮🇸"),
      CountryCode(name: "India", dialCode: "+91", code: "IN", flag: "🇮🇳"),
      CountryCode(name: "Indonesia", dialCode: "+62", code: "ID", flag: "🇮🇩"),
      CountryCode(name: "Iran", dialCode: "+98", code: "IR", flag: "🇮🇷"),
      CountryCode(name: "Iraq", dialCode: "+964", code: "IQ", flag: "🇮🇶"),
      CountryCode(name: "Ireland", dialCode: "+353", code: "IE", flag: "🇮🇪"),
      CountryCode(name: "Israel", dialCode: "+972", code: "IL", flag: "🇮🇱"),
      CountryCode(name: "Italy", dialCode: "+39", code: "IT", flag: "🇮🇹"),
      CountryCode(name: "Jamaica", dialCode: "+1", code: "JM", flag: "🇯🇲"),
      CountryCode(name: "Japan", dialCode: "+81", code: "JP", flag: "🇯🇵"),
      CountryCode(name: "Jordan", dialCode: "+962", code: "JO", flag: "🇯🇴"),
      CountryCode(name: "Kazakhstan", dialCode: "+7", code: "KZ", flag: "🇰🇿"),
      CountryCode(name: "Kenya", dialCode: "+254", code: "KE", flag: "🇰🇪"),
      CountryCode(name: "Kiribati", dialCode: "+686", code: "KI", flag: "🇰🇮"),
      CountryCode(
        name: "North Korea",
        dialCode: "+850",
        code: "KP",
        flag: "🇰🇵",
      ),
      CountryCode(
        name: "South Korea",
        dialCode: "+82",
        code: "KR",
        flag: "🇰🇷",
      ),
      CountryCode(name: "Kuwait", dialCode: "+965", code: "KW", flag: "🇰🇼"),
      CountryCode(
        name: "Kyrgyzstan",
        dialCode: "+996",
        code: "KG",
        flag: "🇰🇬",
      ),
      CountryCode(name: "Laos", dialCode: "+856", code: "LA", flag: "🇱🇦"),
      CountryCode(name: "Latvia", dialCode: "+371", code: "LV", flag: "🇱🇻"),
      CountryCode(name: "Lebanon", dialCode: "+961", code: "LB", flag: "🇱🇧"),
      CountryCode(name: "Lesotho", dialCode: "+266", code: "LS", flag: "🇱🇸"),
      CountryCode(name: "Liberia", dialCode: "+231", code: "LR", flag: "🇱🇷"),
      CountryCode(name: "Libya", dialCode: "+218", code: "LY", flag: "🇱🇾"),
      CountryCode(
        name: "Liechtenstein",
        dialCode: "+423",
        code: "LI",
        flag: "🇱🇮",
      ),
      CountryCode(
        name: "Lithuania",
        dialCode: "+370",
        code: "LT",
        flag: "🇱🇹",
      ),
      CountryCode(
        name: "Luxembourg",
        dialCode: "+352",
        code: "LU",
        flag: "🇱🇺",
      ),
      CountryCode(
        name: "Macedonia",
        dialCode: "+389",
        code: "MK",
        flag: "🇲🇰",
      ),
      CountryCode(
        name: "Madagascar",
        dialCode: "+261",
        code: "MG",
        flag: "🇲🇬",
      ),
      CountryCode(name: "Malawi", dialCode: "+265", code: "MW", flag: "🇲🇼"),
      CountryCode(name: "Malaysia", dialCode: "+60", code: "MY", flag: "🇲🇾"),
      CountryCode(name: "Maldives", dialCode: "+960", code: "MV", flag: "🇲🇻"),
      CountryCode(name: "Mali", dialCode: "+223", code: "ML", flag: "🇲🇱"),
      CountryCode(name: "Malta", dialCode: "+356", code: "MT", flag: "🇲🇹"),
      CountryCode(
        name: "Marshall Islands",
        dialCode: "+692",
        code: "MH",
        flag: "🇲🇭",
      ),
      CountryCode(
        name: "Mauritania",
        dialCode: "+222",
        code: "MR",
        flag: "🇲🇷",
      ),
      CountryCode(
        name: "Mauritius",
        dialCode: "+230",
        code: "MU",
        flag: "🇲🇺",
      ),
      CountryCode(name: "Mexico", dialCode: "+52", code: "MX", flag: "🇲🇽"),
      CountryCode(
        name: "Micronesia",
        dialCode: "+691",
        code: "FM",
        flag: "🇫🇲",
      ),
      CountryCode(name: "Moldova", dialCode: "+373", code: "MD", flag: "🇲🇩"),
      CountryCode(name: "Monaco", dialCode: "+377", code: "MC", flag: "🇲🇨"),
      CountryCode(name: "Mongolia", dialCode: "+976", code: "MN", flag: "🇲🇳"),
      CountryCode(
        name: "Montenegro",
        dialCode: "+382",
        code: "ME",
        flag: "🇲🇪",
      ),
      CountryCode(name: "Morocco", dialCode: "+212", code: "MA", flag: "🇲🇦"),
      CountryCode(
        name: "Mozambique",
        dialCode: "+258",
        code: "MZ",
        flag: "🇲🇿",
      ),
      CountryCode(name: "Myanmar", dialCode: "+95", code: "MM", flag: "🇲🇲"),
      CountryCode(name: "Namibia", dialCode: "+264", code: "NA", flag: "🇳🇦"),
      CountryCode(name: "Nauru", dialCode: "+674", code: "NR", flag: "🇳🇷"),
      CountryCode(name: "Nepal", dialCode: "+977", code: "NP", flag: "🇳🇵"),
      CountryCode(
        name: "Netherlands",
        dialCode: "+31",
        code: "NL",
        flag: "🇳🇱",
      ),
      CountryCode(
        name: "New Zealand",
        dialCode: "+64",
        code: "NZ",
        flag: "🇳🇿",
      ),
      CountryCode(
        name: "Nicaragua",
        dialCode: "+505",
        code: "NI",
        flag: "🇳🇮",
      ),
      CountryCode(name: "Niger", dialCode: "+227", code: "NE", flag: "🇳🇪"),
      CountryCode(name: "Nigeria", dialCode: "+234", code: "NG", flag: "🇳🇬"),
      CountryCode(name: "Norway", dialCode: "+47", code: "NO", flag: "🇳🇴"),
      CountryCode(name: "Oman", dialCode: "+968", code: "OM", flag: "🇴🇲"),
      CountryCode(name: "Pakistan", dialCode: "+92", code: "PK", flag: "🇵🇰"),
      CountryCode(name: "Palau", dialCode: "+680", code: "PW", flag: "🇵🇼"),
      CountryCode(name: "Panama", dialCode: "+507", code: "PA", flag: "🇵🇦"),
      CountryCode(
        name: "Papua New Guinea",
        dialCode: "+675",
        code: "PG",
        flag: "🇵🇬",
      ),
      CountryCode(name: "Paraguay", dialCode: "+595", code: "PY", flag: "🇵🇾"),
      CountryCode(name: "Peru", dialCode: "+51", code: "PE", flag: "🇵🇪"),
      CountryCode(
        name: "Philippines",
        dialCode: "+63",
        code: "PH",
        flag: "🇵🇭",
      ),
      CountryCode(name: "Poland", dialCode: "+48", code: "PL", flag: "🇵🇱"),
      CountryCode(name: "Portugal", dialCode: "+351", code: "PT", flag: "🇵🇹"),
      CountryCode(name: "Qatar", dialCode: "+974", code: "QA", flag: "🇶🇦"),
      CountryCode(name: "Romania", dialCode: "+40", code: "RO", flag: "🇷🇴"),
      CountryCode(name: "Russia", dialCode: "+7", code: "RU", flag: "🇷🇺"),
      CountryCode(name: "Rwanda", dialCode: "+250", code: "RW", flag: "🇷🇼"),
      CountryCode(
        name: "Saint Kitts and Nevis",
        dialCode: "+1",
        code: "KN",
        flag: "🇰🇳",
      ),
      CountryCode(
        name: "Saint Lucia",
        dialCode: "+1",
        code: "LC",
        flag: "🇱🇨",
      ),
      CountryCode(
        name: "Saint Vincent and the Grenadines",
        dialCode: "+1",
        code: "VC",
        flag: "🇻🇨",
      ),
      CountryCode(name: "Samoa", dialCode: "+685", code: "WS", flag: "🇼🇸"),
      CountryCode(
        name: "San Marino",
        dialCode: "+378",
        code: "SM",
        flag: "🇸🇲",
      ),
      CountryCode(
        name: "Sao Tome and Principe",
        dialCode: "+239",
        code: "ST",
        flag: "🇸🇹",
      ),
      CountryCode(
        name: "Saudi Arabia",
        dialCode: "+966",
        code: "SA",
        flag: "🇸🇦",
      ),
      CountryCode(name: "Senegal", dialCode: "+221", code: "SN", flag: "🇸🇳"),
      CountryCode(name: "Serbia", dialCode: "+381", code: "RS", flag: "🇷🇸"),
      CountryCode(
        name: "Seychelles",
        dialCode: "+248",
        code: "SC",
        flag: "🇸🇨",
      ),
      CountryCode(
        name: "Sierra Leone",
        dialCode: "+232",
        code: "SL",
        flag: "🇸🇱",
      ),
      CountryCode(name: "Singapore", dialCode: "+65", code: "SG", flag: "🇸🇬"),
      CountryCode(name: "Slovakia", dialCode: "+421", code: "SK", flag: "🇸🇰"),
      CountryCode(name: "Slovenia", dialCode: "+386", code: "SI", flag: "🇸🇮"),
      CountryCode(
        name: "Solomon Islands",
        dialCode: "+677",
        code: "SB",
        flag: "🇸🇧",
      ),
      CountryCode(name: "Somalia", dialCode: "+252", code: "SO", flag: "🇸🇴"),
      CountryCode(
        name: "South Africa",
        dialCode: "+27",
        code: "ZA",
        flag: "🇿🇦",
      ),
      CountryCode(
        name: "South Sudan",
        dialCode: "+211",
        code: "SS",
        flag: "🇸🇸",
      ),
      CountryCode(name: "Spain", dialCode: "+34", code: "ES", flag: "🇪🇸"),
      CountryCode(name: "Sri Lanka", dialCode: "+94", code: "LK", flag: "🇱🇰"),
      CountryCode(name: "Sudan", dialCode: "+249", code: "SD", flag: "🇸🇩"),
      CountryCode(name: "Suriname", dialCode: "+597", code: "SR", flag: "🇸🇷"),
      CountryCode(
        name: "Swaziland",
        dialCode: "+268",
        code: "SZ",
        flag: "🇸🇿",
      ),
      CountryCode(name: "Sweden", dialCode: "+46", code: "SE", flag: "🇸🇪"),
      CountryCode(
        name: "Switzerland",
        dialCode: "+41",
        code: "CH",
        flag: "🇨🇭",
      ),
      CountryCode(name: "Syria", dialCode: "+963", code: "SY", flag: "🇸🇾"),
      CountryCode(name: "Taiwan", dialCode: "+886", code: "TW", flag: "🇹🇼"),
      CountryCode(
        name: "Tajikistan",
        dialCode: "+992",
        code: "TJ",
        flag: "🇹🇯",
      ),
      CountryCode(name: "Tanzania", dialCode: "+255", code: "TZ", flag: "🇹🇿"),
      CountryCode(name: "Thailand", dialCode: "+66", code: "TH", flag: "🇹🇭"),
      CountryCode(name: "Togo", dialCode: "+228", code: "TG", flag: "🇹🇬"),
      CountryCode(name: "Tonga", dialCode: "+676", code: "TO", flag: "🇹🇴"),
      CountryCode(
        name: "Trinidad and Tobago",
        dialCode: "+1",
        code: "TT",
        flag: "🇹🇹",
      ),
      CountryCode(name: "Tunisia", dialCode: "+216", code: "TN", flag: "🇹🇳"),
      CountryCode(name: "Turkey", dialCode: "+90", code: "TR", flag: "🇹🇷"),
      CountryCode(
        name: "Turkmenistan",
        dialCode: "+993",
        code: "TM",
        flag: "🇹🇲",
      ),
      CountryCode(name: "Tuvalu", dialCode: "+688", code: "TV", flag: "🇹🇻"),
      CountryCode(name: "Uganda", dialCode: "+256", code: "UG", flag: "🇺🇬"),
      CountryCode(name: "Ukraine", dialCode: "+380", code: "UA", flag: "🇺🇦"),
      CountryCode(
        name: "United Arab Emirates",
        dialCode: "+971",
        code: "AE",
        flag: "🇦🇪",
      ),
      CountryCode(
        name: "United Kingdom",
        dialCode: "+44",
        code: "GB",
        flag: "🇬🇧",
      ),
      CountryCode(
        name: "United States",
        dialCode: "+1",
        code: "US",
        flag: "🇺🇸",
      ),
      CountryCode(name: "Uruguay", dialCode: "+598", code: "UY", flag: "🇺🇾"),
      CountryCode(
        name: "Uzbekistan",
        dialCode: "+998",
        code: "UZ",
        flag: "🇺🇿",
      ),
      CountryCode(name: "Vanuatu", dialCode: "+678", code: "VU", flag: "🇻🇺"),
      CountryCode(
        name: "Vatican City",
        dialCode: "+39",
        code: "VA",
        flag: "🇻🇦",
      ),
      CountryCode(name: "Venezuela", dialCode: "+58", code: "VE", flag: "🇻🇪"),
      CountryCode(name: "Vietnam", dialCode: "+84", code: "VN", flag: "🇻🇳"),
      CountryCode(name: "Yemen", dialCode: "+967", code: "YE", flag: "🇾🇪"),
      CountryCode(name: "Zambia", dialCode: "+260", code: "ZM", flag: "🇿🇲"),
      CountryCode(name: "Zimbabwe", dialCode: "+263", code: "ZW", flag: "🇿🇼"),
    ];
  }
}
